G++ gives this error since GCC version 4.1:
In file included from src/core/cachefilter.h:24:0,
                 from src/core/cachefilter.cpp:21:
src/core/vscore.h:502:17: error: extra qualification 'VSThreadPool::' on member 'taskCmp' [-fpermissive]